[project]
name = "Nutrilog"
version = "0.1.0"
description = "Nutrition tracking app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "uvicorn",
    "requests",
    "dotenv>=0.9.9",
]
